/** Taxonomias fixas (custo zero) — slugs em português. */

export const CATEGORIAS_PRINCIPAIS = [
  'motivacao',
  'reflexao',
  'amor',
  'amizade',
  'sabedoria',
  'trabalho',
  'lideranca',
  'educacao',
  'familia',
  'sucesso',
  'superacao',
  'fe',
  'espiritualidade',
  'autoestima',
  'gratidao',
  'felicidade',
  'tempo',
  'vida',
  'coragem',
  'inteligencia',
  'humor',
  'negocios',
  'empreendedorismo',
  'saude-mental',
  'desenvolvimento-pessoal',
] as const;

export const CONTEXTOS = [
  'dia-chuvoso',
  'segunda-feira',
  'bom-dia',
  'boa-noite',
  'termino',
  'casamento',
  'luto',
  'recomeco',
  'mudanca',
  'aniversario',
  'formatura',
  'natal',
  'ano-novo',
  'trabalho',
  'estudos',
  'academia',
  'viagem',
  'inspiracao',
  'reflexao-noturna',
] as const;

export const EMOCOES = [
  'esperanca',
  'tristeza',
  'alegria',
  'gratidao',
  'coragem',
  'amor',
  'saudade',
  'paz',
  'motivacao',
  'determinacao',
  'felicidade',
  'ansiedade',
  'serenidade',
] as const;

type KeywordMap = Record<string, string[]>;

export const CATEGORIA_KEYWORDS: KeywordMap = {
  motivacao: ['motivat', 'inspir', 'dream', 'goal', 'persist', 'never give', 'keep going', 'ânimo', 'força'],
  reflexao: ['think', 'life', 'meaning', 'wisdom', 'truth', 'soul', 'mind', 'reflex', 'pensar', 'exist'],
  amor: ['love', 'heart', 'romance', 'kiss', 'marry', 'amor', 'carinho', 'paixão'],
  amizade: ['friend', 'friendship', 'amigo', 'amizade'],
  sabedoria: ['wisdom', 'wise', 'knowledge', 'learn', 'sabedoria', 'sábio'],
  trabalho: ['work', 'job', 'career', 'office', 'trabalho', 'profiss'],
  lideranca: ['lead', 'leader', 'team', 'lider', 'gestão'],
  educacao: ['learn', 'school', 'teach', 'study', 'education', 'educ'],
  familia: ['family', 'mother', 'father', 'child', 'família', 'filho', 'pai', 'mãe'],
  sucesso: ['success', 'win', 'achiev', 'sucesso', 'vencer'],
  superacao: ['overcome', 'adversity', 'resilien', 'superar', 'superação'],
  fe: ['faith', 'god', 'pray', 'religion', 'fé', 'deus', 'spirit'],
  espiritualidade: ['spiritual', 'soul', 'divine', 'espiritual', 'alma'],
  autoestima: ['self', 'esteem', 'worth', 'confidence', 'autoestima'],
  gratidao: ['grateful', 'thank', 'gratitude', 'gratidão'],
  felicidade: ['happy', 'happiness', 'joy', 'feliz', 'alegria'],
  tempo: ['time', 'moment', 'today', 'tomorrow', 'tempo', 'hora'],
  vida: ['life', 'live', 'living', 'vida', 'viver'],
  coragem: ['courage', 'brave', 'fear', 'coragem', 'medo'],
  inteligencia: ['intelligence', 'smart', 'brain', 'intelig'],
  humor: ['laugh', 'funny', 'humor', 'joke', 'rir'],
  negocios: ['business', 'money', 'profit', 'market', 'negócio'],
  empreendedorismo: ['entrepreneur', 'startup', 'founder', 'empreend'],
  'saude-mental': ['mental', 'anxiety', 'therapy', 'peace of mind', 'saúde mental'],
  'desenvolvimento-pessoal': ['grow', 'improve', 'habit', 'self-help', 'desenvolvimento'],
};

export const CONTEXTO_KEYWORDS: KeywordMap = {
  'dia-chuvoso': ['rain', 'rainy', 'chuva', 'storm'],
  'segunda-feira': ['monday', 'segunda'],
  'bom-dia': ['good morning', 'bom dia', 'morning'],
  'boa-noite': ['good night', 'boa noite', 'night'],
  termino: ['breakup', 'end', 'goodbye', 'término', 'separar'],
  casamento: ['wedding', 'marry', 'marriage', 'casamento'],
  luto: ['grief', 'death', 'loss', 'luto', 'morreu'],
  recomeco: ['restart', 'begin again', 'recomeço', 'new start'],
  mudanca: ['change', 'mudança', 'transform'],
  aniversario: ['birthday', 'aniversário'],
  formatura: ['graduation', 'formatura'],
  natal: ['christmas', 'natal'],
  'ano-novo': ['new year', 'ano novo'],
  trabalho: ['work', 'office', 'trabalho'],
  estudos: ['study', 'exam', 'estudo', 'escola'],
  academia: ['gym', 'fitness', 'workout', 'academia'],
  viagem: ['travel', 'journey', 'viagem', 'road'],
  inspiracao: ['inspir', 'inspire'],
  'reflexao-noturna': ['night', 'dark', 'silence', 'noturn'],
};

export const EMOCAO_KEYWORDS: KeywordMap = {
  esperanca: ['hope', 'esperança', 'future'],
  tristeza: ['sad', 'triste', 'cry', 'tear', 'sorrow'],
  alegria: ['joy', 'happy', 'alegria', 'smile'],
  gratidao: ['grateful', 'thank', 'gratidão'],
  coragem: ['courage', 'brave', 'coragem'],
  amor: ['love', 'amor', 'heart'],
  saudade: ['miss', 'saudade', 'longing'],
  paz: ['peace', 'calm', 'paz', 'serene'],
  motivacao: ['motivat', 'drive', 'ambition'],
  determinacao: ['determin', 'persist', 'never'],
  felicidade: ['happy', 'happiness', 'felic'],
  ansiedade: ['anxiety', 'worry', 'ansiedade', 'stress'],
  serenidade: ['serene', 'tranquil', 'quiet mind'],
};
