import type { CollectionConfig } from '../types';

/** Coleções premium por intenção emocional — paletas fixas (sem cores aleatórias). */
export const SEMANTIC_COLLECTIONS: CollectionConfig[] = [
  {
    id: 'motivacao',
    name: 'Motivação',
    emoji: '☀️',
    theme: 'Luz, horizonte e conquista',
    skins: [
      {
        id: 'aurora',
        name: 'Aurora',
        category: 'motivacao',
        bgClass: 'bg-gradient-to-br from-amber-200/90 via-orange-100 to-sky-200',
        textClass: 'text-amber-950',
        accentClass: 'text-amber-800/75',
        borderClass: 'border-amber-300/40',
        cardStyle: {
          backgroundImage:
            'linear-gradient(165deg, rgba(251,191,36,0.35) 0%, rgba(255,255,255,0.15) 40%, rgba(56,189,248,0.2) 100%)',
        },
        palette: {
          primary: '#F59E0B',
          secondary: '#FDE68A',
          accent: '#38BDF8',
          contrast: '#451A03',
        },
      },
      {
        id: 'horizonte',
        name: 'Horizonte',
        category: 'motivacao',
        bgClass: 'bg-gradient-to-br from-slate-900 via-amber-900/40 to-slate-950',
        textClass: 'text-amber-50',
        accentClass: 'text-amber-200/70',
        borderClass: 'border-amber-500/25',
        palette: {
          primary: '#D97706',
          secondary: '#1E293B',
          accent: '#FBBF24',
          contrast: '#FFFBEB',
        },
      },
    ],
  },
  {
    id: 'amor',
    name: 'Amor',
    emoji: '❤️',
    theme: 'Calor romântico e elegância',
    skins: [
      {
        id: 'rosa-suave',
        name: 'Rosa Suave',
        category: 'amor',
        bgClass: 'bg-gradient-to-br from-rose-100 via-pink-50 to-rose-200',
        textClass: 'text-rose-950',
        accentClass: 'text-rose-700/80',
        borderClass: 'border-rose-200/70',
        palette: {
          primary: '#FB7185',
          secondary: '#FECDD3',
          accent: '#F43F5E',
          contrast: '#4C0519',
        },
      },
      {
        id: 'paixao',
        name: 'Paixão',
        category: 'amor',
        bgClass: 'bg-gradient-to-br from-rose-950 via-red-900 to-rose-950',
        textClass: 'text-rose-50',
        accentClass: 'text-rose-200/75',
        borderClass: 'border-rose-400/30',
        palette: {
          primary: '#E11D48',
          secondary: '#881337',
          accent: '#FDA4AF',
          contrast: '#FFF1F2',
        },
      },
    ],
  },
  {
    id: 'reflexao',
    name: 'Reflexão',
    emoji: '🪞',
    theme: 'Minimalismo sofisticado',
    skins: [
      {
        id: 'neutro',
        name: 'Neutro',
        category: 'reflexao',
        bgClass: 'bg-gradient-to-br from-stone-100 via-zinc-50 to-stone-200',
        textClass: 'text-stone-900',
        accentClass: 'text-stone-600/85',
        borderClass: 'border-stone-300/50',
        palette: {
          primary: '#78716C',
          secondary: '#E7E5E4',
          accent: '#A8A29E',
          contrast: '#1C1917',
        },
      },
      {
        id: 'noite',
        name: 'Noite',
        category: 'reflexao',
        bgClass: 'bg-gradient-to-br from-zinc-900 via-neutral-900 to-black',
        textClass: 'text-zinc-100',
        accentClass: 'text-zinc-400/80',
        borderClass: 'border-zinc-600/35',
        palette: {
          primary: '#52525B',
          secondary: '#27272A',
          accent: '#A1A1AA',
          contrast: '#FAFAFA',
        },
      },
    ],
  },
  {
    id: 'metaforas',
    name: 'Metáforas',
    emoji: '🎭',
    theme: 'Arte simbólica e contemplação',
    skins: [
      {
        id: 'atelie',
        name: 'Ateliê',
        category: 'metaforas',
        bgClass: 'bg-gradient-to-br from-violet-950 via-purple-900 to-indigo-950',
        textClass: 'text-violet-50',
        accentClass: 'text-violet-200/75',
        borderClass: 'border-violet-400/25',
        cardStyle: { boxShadow: 'inset 0 0 100px rgba(139,92,246,0.2)' },
        palette: {
          primary: '#7C3AED',
          secondary: '#4C1D95',
          accent: '#C4B5FD',
          contrast: '#F5F3FF',
        },
      },
      {
        id: 'agua-profunda',
        name: 'Água Profunda',
        category: 'metaforas',
        bgClass: 'bg-gradient-to-br from-teal-950 via-cyan-950 to-slate-950',
        textClass: 'text-cyan-50',
        accentClass: 'text-teal-200/70',
        borderClass: 'border-cyan-500/25',
        palette: {
          primary: '#0D9488',
          secondary: '#134E4A',
          accent: '#5EEAD4',
          contrast: '#F0FDFA',
        },
      },
    ],
  },
  {
    id: 'superacao',
    name: 'Superação',
    emoji: '⚡',
    theme: 'Energia e vitória equilibrada',
    skins: [
      {
        id: 'ascensao',
        name: 'Ascensão',
        category: 'superacao',
        bgClass: 'bg-gradient-to-br from-orange-600 via-amber-700 to-slate-950',
        textClass: 'text-white',
        accentClass: 'text-amber-100/85',
        borderClass: 'border-orange-400/35',
        palette: {
          primary: '#EA580C',
          secondary: '#1E293B',
          accent: '#FCD34D',
          contrast: '#FFFFFF',
        },
      },
      {
        id: 'vitoria',
        name: 'Vitória',
        category: 'superacao',
        bgClass: 'bg-gradient-to-br from-emerald-800 via-green-900 to-black',
        textClass: 'text-emerald-50',
        accentClass: 'text-emerald-200/80',
        borderClass: 'border-emerald-400/30',
        palette: {
          primary: '#059669',
          secondary: '#14532D',
          accent: '#6EE7B7',
          contrast: '#ECFDF5',
        },
      },
    ],
  },
];
